export const LOGIN_AUTH_API = 'https://backend-lasgambusinas.onrender.com/api/mozos/auth';
export const COMANDA_API = 'https://backend-lasgambusinas.onrender.com/api/comanda';
export const DISHES_API = 'https://backend-lasgambusinas.onrender.com/api/platos';
export const COMANDASEARCH_API_GET = 'https://backend-lasgambusinas.onrender.com/api/comanda';
export const SELECTABLE_API_GET = 'https://backend-lasgambusinas.onrender.com/api/mesas';
export const COMANDA_API_SEARCH_BY_DATE ='https://backend-lasgambusinas.onrender.com/api/comanda/fecha';
// export const LOGIN_AUTH_API = 'http://192.168.1.4:8000/api/mozos/auth';
// export const COMANDA_API = 'http://192.168.1.4:8000/api/comanda';
// export const DISHES_API = 'http://192.168.1.4:8000/api/platos';
// export const COMANDASEARCH_API_GET = 'http://192.168.1.4:8000/api/comanda';
// export const SELECTABLE_API_GET = 'http://192.168.1.4:8000/api/mesas';
// export const COMANDA_API_SEARCH_BY_DATE ='http://192.168.1.4:8000/api/comanda/fecha'